### ISSUE TITLE
Unable to keep database after refreshing

### ISSUE THREAD

**Issue by Fishdrowned** [hollodotme/readis#12]
## Expected Behavior
Select a database and refresh the page, the database should remain selected

## Actual Behavior
Select a database and refresh the page, the database is reset to 0

## Steps to Reproduce the Problem

1. Open readis in a browser
2. Select a database
3. Refresh the page

**Comment by hollodotme** [comment]
Thank you for the issue and PR. I needed to fix your URL substring at https://github.com/hollodotme/readis/blob/master/public/js/Keys.js#L26 to make it work.

Very useful enhancement. I also added you as contributor to the LICENSE file.
New release v2.2.0 is out.
