### ISSUE TITLE
Auth parameter does not work

### ISSUE THREAD

**Issue by jeff1985** [hollodotme/readis#18]
The auth parameter in `config/servers.php` does not seem to work. I tried providing auth parameter as following
```
<?php declare(strict_types=1);

return [
    [
        'name'          => 'Local Redis',
        'host'          => '192.168.100.1',
        'port'          => 6379,
        'auth'          => 'XXX',
        ....
```

 for my redis server running with `--requirepass XXX` parameter. In this case I'm not able to connect.  

I verified that the connection does work if I just use redis-cli. Also If I leave out the --requirepass for my redis server, the connection with readis UI works fine (even if I specify the password under `config/servers.php`). 

I also looked into https://github.com/hollodotme/readis/blob/a2e83f3192b26560394e551d4ffa77d26431f00f/src/Infrastructure/Redis/RedisWrapper.php and there seems to be no auth handling in this class. Is it not yet implemented?

**Comment by hollodotme** [comment]
Hi @jeff1985, 

thank you for the issue. You're right, the auth feature is missing in the mentioned wrapper.
I'll add it now and release it with `v2.2.1`.

**Comment by hollodotme** [comment]
Done. 😃

**Comment by jeff1985** [comment]
Thanks a lot for fixing it so fast! Works fine for me!  ;)
