### ISSUE TITLE
Database map doesn't seem to work

### ISSUE THREAD

**Issue by bmvzane** [hollodotme/readis#8]
## Expected Behavior
Server config database number is set to 1, nothing else in array. Keys shown should be from database 1.

## Actual Behavior
Still pulls and shows keys from database 0.

## Steps to Reproduce the Problem
```
        [
		'name'          => 'Local redis server 1',
		'host'          => '127.0.0.1',
		'port'          => 6379,
		'timeout'       => 2.5,
		'retryInterval' => 100,
		'auth'          => null,
		'databaseMap'   => [
			'1' => 'Sample Data',
		],
	]
```

## Specifications

- Package version: v2.0.0
- PHP version: 7.1
- Platform/OS: Ubuntu Server 16.04

**Comment by hollodotme** [comment]
Please have a look at the [documentation](https://github.com/hollodotme/readis/blob/master/README.md#sample-server-configuration):
>You can map the numeric database keys to plain text names. Keys that were not mapped will still be displayed as `Database [KEY]`.

The database map is supposed to give the numeric database keys names only. It is not meant as the config of how many databases are available or shown. That must be set in the redis-server config.

Your config should look like this in the UI:
<img width="641" alt="screen shot 2018-05-01 at 08 43 24" src="https://user-images.githubusercontent.com/1557839/39464080-c1b44a9c-4d1b-11e8-9ebc-21af56ee8e06.png">

**Comment by bmvzane** [comment]
Thanks for taking the time to look at the issue I'm having. It's a great project to use.

So I was playing around with it and tested locally, it works perfectly fine illustrated. However, it doesn't seem to work with AWS elasticache redis server. There are certain redis commands disabled like CONFIG commands. I'm guessing the project is using CONFIG GET databases? I was trying to find it in code but I couldn't find it. If it is, would it be possible to make it rely on the databases declared in the config file instead?

Here's what I see with the elasticache setup:
config:
![screen shot 2018-05-01 at 1 41 23 pm](https://user-images.githubusercontent.com/8365762/39501748-7714c600-4d71-11e8-88c7-64eb6f39faf3.png)
default on db 0:
![screen shot 2018-05-01 at 6 48 57 pm](https://user-images.githubusercontent.com/8365762/39501753-830f48d6-4d71-11e8-91a3-f53f6a8a6845.png)
selected db 1:
![screen shot 2018-05-01 at 6 49 28 pm](https://user-images.githubusercontent.com/8365762/39501765-94fb9162-4d71-11e8-9154-8be41658ed57.png)
![screen shot 2018-05-01 at 6 49 49 pm](https://user-images.githubusercontent.com/8365762/39501792-ad90e420-4d71-11e8-9593-65433ad267a7.png)

**Comment by hollodotme** [comment]
@bmvzane Thanks for the elaboration. I surely an add an option so that a manually defined list of databases is used for the application and the database map. 

Question though: If the `CONFIG GET` commands are disabled the "Config" and "Monitor" tab won't work either, correct?

**Comment by bmvzane** [comment]
The "Info" and "Monitor" tabs work. The "Config" tab doesn't.

Info
![screen shot 2018-05-02 at 12 19 24 pm](https://user-images.githubusercontent.com/8365762/39544500-1c913870-4e03-11e8-8c17-970d2db39fb9.png)

Config
![screen shot 2018-05-02 at 12 13 48 pm](https://user-images.githubusercontent.com/8365762/39544451-f38059c0-4e02-11e8-9b43-5d16f0a5dca0.png)

Monitor
![screen shot 2018-05-02 at 12 13 38 pm](https://user-images.githubusercontent.com/8365762/39544452-f4ac1514-4e02-11e8-9570-1b4ed53b71d5.png)

**Comment by hollodotme** [comment]
@bmvzane Alright, thanks for the info. I will take care of it as soon as I can.

**Comment by hollodotme** [comment]
Self-note: for reproduction, this is how disabling commands in redis work:
```
rename-command CONFIG ""
```

**Comment by hollodotme** [comment]
@bmvzane Can you provide the output of the following commands from the AWS instance?

* `redis-cli > CONFIG GET *`
* `redis-cli > INFO`

Your screenshot implies that the CONFIG command is *not* disabled, but its return values manipulated somehow. If I disable the CONFIG command completely,  the application is not even able to connect to the server.

Thanks.

**Comment by nagaraju02** [comment]
When I used the below commands from an AWS instance the outputs are as follows:
redis-cli > CONFIG GET *
redis-cli > INFO

<img width="851" alt="screen shot 2018-05-11 at 12 21 22 pm" src="https://user-images.githubusercontent.com/27576816/39942951-fe781f10-5515-11e8-903f-6b7eb25cbe88.png">

Seems INFO is working and CONFIG GET * errors out.

**Comment by hollodotme** [comment]
Thanks!

**Comment by hollodotme** [comment]
@bmvzane, @nagaraju02 The new release v2.1.0 is out including docker image at https://hub.docker.com/r/hollodotme/readis/ and demo at https://readis.hollo.me/.

I hope you'll like it. 😃

**Comment by nagaraju02** [comment]
Will try the new version thanks!!

**Comment by bmvzane** [comment]
@hollodotme This looks really awesome! Thanks a lot!
