### ISSUE TITLE
Unable to view items from lists, sets, etc

### ISSUE THREAD

**Issue by bmvzane** [hollodotme/readis#9]
It would be great to have this feature. Just not sure if there are complicated issues related to it.

**Comment by hollodotme** [comment]
I will have a look at the other data structures and try to add them.

**Comment by hollodotme** [comment]
I have added output handling for lists, sets and sorted sets. Also it is possible now to view all elements/fields/members of lists/hashes/(sorted) sets in one view.

![image](https://user-images.githubusercontent.com/1557839/39958293-5f97b896-5601-11e8-9a5f-df05e1779221.png)

Unfortunately it is not possible to clearly distinct between custom sorted sets and those containing GEO data, so I was not able to add some luxery output for GEO data, like linking to OpenStreetMap etc. And - for now - I could not find a proper way to display HyperLogLog encoded strings in a human readable way. Maybe both in a later release.

**Comment by bmvzane** [comment]
Awesome! This looks really cool. Thanks a lot! I'll give it a try and let you know how it goes.

**Comment by hollodotme** [comment]
Wait until tomorrow, I plan to finish the next release today/tomorrow. :)

**Comment by bmvzane** [comment]
Alright will do. Thanks!
